version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: python_shop
      MYSQL_USER: python_app_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root --password=$$(cat /run/secrets/mysql_root_password) -e 'SELECT 1'"]
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - mysql-network
    secrets:
      - mysql_root_password
      - mysql_password

  python_testing_app:
    tty: true
    image: ghcr.io/wincchesster/actions-build-tests:tests
    build:
      context: .
      dockerfile: Dockerfile_tests
    environment:
      DB_HOST: mysql
      DB_USER: python_app_user
      DB_PASSWORD_FILE: /run/secrets/mysql_password
      DB_DATABASE: python_shop
    ports:
      - "80:8000"
    depends_on:
      - mysql
    networks:
      - mysql-network

  app-coverage:
    tty: true
    image: ghcr.io/wincchesster/actions-build-tests:tests
    build:
      context: .
      dockerfile: Dockerfile_tests
    environment:
      DB_HOST: mysql
      DB_USER: python_app_user
      DB_PASSWORD_FILE: /run/secrets/mysql_password
      DB_DATABASE: python_shop
    entrypoint: "coverage run -m unittest test.py && coverage report -m && coverage html -d coverage"
    volumes:
      - ./coverage:/app/coverage
    ports:
      - "80:8000"
    depends_on:
      - mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

secrets:
  mysql_root_password:
    file: .env_mysql_root_password
  mysql_password:
    file: .env_mysql_password
