version: '3.9'

services:
  mysql:
    container_name: mysql-server
    image: mysql:latest
    environment:
      # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: python_shop
      MYSQL_USER: python_app_user
      # MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    # healthcheck:
    #   test: ["CMD-SHELL", "mysql -u root --password=$$(cat /run/secrets/mysql_root_password) -e 'SELECT 1'"]
    #   interval: 1s
    #   timeout: 2s
    #   retries: 5
    networks:
      - mysql-network
    # secrets:
    #   - mysql_root_password
    #   - mysql_password

  python_testing_app:
    container_name: python_testing_container
    tty: true
    image: ghcr.io/wincchesster/actions-build-tests:tests
    build:
      context: .
      dockerfile: Dockerfile_tests
    environment:
      DB_HOST: mysql
      DB_USER: python_app_user
      # DB_PASSWORD_FILE: /run/secrets/mysql_password
      DB_PASSWORD: password
      DB_DATABASE: python_shop
    ports:
      - "80:8000"
    depends_on:
      - mysql
    networks:
      - mysql-network

  app-coverage:
    container_name: app-coverage
    tty: true
    image: ghcr.io/wincchesster/actions-build-tests:tests
    build:
      context: .
      dockerfile: Dockerfile_tests
    environment:
      DB_HOST: mysql
      DB_USER: python_app_user
      # DB_PASSWORD_FILE: /run/secrets/mysql_password
      DB_PASSWORD: password
      DB_DATABASE: python_shop
    entrypoint: >
      sh -c "coverage run -m unittest test.py &&
               coverage report -m &&
               coverage html -d /app/coverage
               cat /app/coverage/index.html
               echo 'Coverage report generated in /app/coverage'"
    # volumes:
    #   - ./coverage:/app/coverage
    ports:
      - "80:8000"
    depends_on:
      - mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

# secrets:
#   mysql_root_password:
#     file: .env_mysql_root_password
#   mysql_password:
#     file: .env_mysql_password
