name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:

    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Build
              run: |
                    \docker build -t testimage .