name: Build

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

  
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
